source .env

echo "POSTGRES_HOST: $POSTGRES_HOST"
echo "POSTGRES_USER: $POSTGRES_USER"
echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
echo "POSTGRES_DB: $POSTGRES_DB"
echo "POSTGRES_PORT: $POSTGRES_PORT"
echo "POSTGRES_SSLMODE: $POSTGRES_SSLMODE"

export PGPASSWORD=$POSTGRES_PASSWORD

psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT
