version: "3.8"

services:
    postgres:
        image: postgres:15-alpine
        container_name: smashfriend-postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-smashfriend}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-smashfriend}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
